- dev-template.html
- src/components/AddToCartButton/AddToCartButton.tsx
- src/components/ProductItem/ProductItem.tsx
- src/components/ProductItem/ProductPrice.tsx
- src/components/SwatchButton/SwatchButton.tsx
- src/components/SwatchButtonGroup/SwatchButtonGroup.tsx
- src/context/cart.tsx
- src/context/products.tsx
- src/styles/index.css
- src/styles/tokens.css
- src/types/interface.ts
This PR fixes
1. Add support for size swatches (visible when clicked on "Quick Add" button
2. Fix paddings / gaps in PLP card.
3. Add correct meta tags for responsiveness 
4. Make image hover transition faster
> WAF-120: Add size swatches support and fix plp card paddings

- src/components/Pagination/Pagination.tsx
- src/styles/index.css
Fixes:
1. Back button text changed to "Previous"
2. Add an underline to the text on hover for active buttons
> WAF-52: Pagination fix

- src/components/Enrichment/Enrichment.stories.mdx
- src/components/Enrichment/Enrichment.tsx
- src/components/Enrichment/index.ts
- src/containers/App.tsx
[WAF-104](https://amersports.atlassian.net/browse/WAF-104)
Added containers for enrichemnt.js to position plp blocks in right places.
> WAF-104 - Adder containers for eds promos

- src/components/ImageHover/ImageHover.tsx
- src/components/ProductItem/ProductItem.tsx
- src/components/ProductItem/ProductPrice.tsx
- src/types/interface.ts
- src/utils/getProductPrice.ts
Added necessary microdata per product
> WAF-70 Add necessary PLP schema

- src/components/ProductItem/ProductItem.tsx
- src/components/ProductItem/ProductPrice.tsx
Price styling changes : For “ON SALE” please change the Regular Price to grey and the Special Price to black
> Price styling on PLP

- README.md
- src/components/AddToCartButton/AddToCartButton.tsx
- src/components/ProductItem/ProductItem.tsx
- src/components/ProductList/ProductList.tsx
- src/components/SwatchButtonGroup/SwatchButtonGroup.tsx
- src/containers/App.tsx
- src/context/products.tsx
- src/i18n/en_US.ts
- src/styles/index.css
- src/styles/tokens.css
- src/types/interface.ts
Related PR: https://github.com/aemsites/wilson/pull/275
> WAF-120: Add attribute check for quick add button

- dev-template.html
- src/components/Facets/Facets.tsx
- src/components/FilterSelection/FilterSelectionGroup.tsx
- src/components/InputButtonGroup/InputButtonGroup.tsx
- src/components/LabelledInput/LabelledInput.tsx
- src/components/ProductItem/ProductItem.test.tsx
- src/components/ProductItem/ProductPrice.tsx
- src/context/products.tsx
- src/context/store.tsx
- src/types/interface.ts
- src/utils/tests/utils.test.ts
- tsconfig.json
Support category filter
Made `npm run dev` run again
> WAF-294 Category filters

- src/api/search.ts
adding filter for not fetch discontinued product
> [WIL] PLP - Product Graveyard

- dev-template.html
- src/context/products.tsx
- src/types/interface.ts
Feature to allow certain filters to be preset on page load via configuration
> WAF-41 - prechecked filters for custom category

- src/api/search.ts
- src/components/Facets/SelectedFilters.tsx
- src/components/InputButtonGroup/InputButtonGroup.tsx
- src/components/ProductItem/ProductItem.test.tsx
- src/components/ProductItem/ProductPrice.tsx
- src/components/ProductList/ProductList.test.tsx
- src/components/ProductList/ProductList.tsx
- src/containers/App.tsx
- src/containers/ProductsHeader.tsx
- src/context/products.tsx
- src/context/search.tsx
- src/context/store.tsx
- src/utils/getProductPrice.ts
- src/utils/tests/utils.test.ts
Related wilson PR: https://github.com/aemsites/wilson/pull/309
> Fix lint and build errors

- src/api/search.ts
- src/components/Facets/SelectedFilters.tsx
- src/components/ProductList/ProductList.tsx
- src/components/ProductList/product-list.css
- src/containers/App.tsx
- src/context/products.tsx
- src/context/search.tsx
- src/types/interface.ts
Following issues are fixed
1. Remove displayByFranchise from store config and derive it from categoryConfig
2. Add salability filter for franchise query
3. Fix CSS
Related wilson PR: https://github.com/aemsites/wilson/pull/310
> WAF-145: Address feedback points

- src/api/search.ts
- src/components/ProductList/ProductList.tsx
- src/context/products.tsx
Related wilson PR: https://github.com/aemsites/wilson/pull/318
> WAF-145: Fix franchise pagination

- src/components/Facets/Facets.tsx
Fix for removed facets.css in WAF-296 ticket
> WAF-296 - Fix for facets css

- src/components/FilterSelection/FilterSelectionGroup.tsx
- src/components/ProductItem/ProductItem.tsx
related wilson PR: https://github.com/wilson-ecommerce/eds-amersports/pull/5
> WAF-146: Fix hover effect and category filter display in PLP

- src/api/queries.ts
- src/components/ProductItem/ProductItem.tsx
- src/components/SwatchButtonGroup/SwatchButtonGroup.test.tsx
- src/components/SwatchButtonGroup/SwatchButtonGroup.tsx
- src/types/interface.ts
- src/utils/getProductImage.ts
- src/utils/productUtils.ts
Related PR: https://github.com/wilson-ecommerce/eds-amersports/pull/27
> WAF-394: Add swatches for sportswear PLP

- src/utils/productUtils.ts
Related EDS PR: https://github.com/wilson-ecommerce/eds-amersports/pull/32
> Fix null pointer exception when some search results doesn't have color swatches

- src/components/Facets/Facets.tsx
- src/components/Facets/ToggleFilters.tsx
- src/components/FilterSelection/FilterSelection.tsx
- src/components/InputButtonGroup/InputButtonGroup.tsx
- src/components/SortDropdown/SortDropdown.tsx
[WAF-396](https://amersports.atlassian.net/browse/WAF-396) ticket fixes and code review changes
> WAF-396 - Fix and changes requested at code review

- src/components/CategoryFilters/CategoryFilters.tsx
- src/components/Drawer/Drawer.tsx
- src/components/Facets/Facets.tsx
- src/components/Facets/Range/RangeFacet.tsx
- src/components/Facets/Scalar/ScalarFacet.test.tsx
- src/components/Facets/ToggleFilters.tsx
- src/components/Facets/filters.css
- src/components/FilterSelection/FilterSelection.test.tsx
- src/components/FilterSelection/FilterSelection.tsx
- src/components/InputButtonGroup/InputButtonGroup.test.tsx
- src/components/InputButtonGroup/InputButtonGroup.tsx
- src/components/LabelledInput/LabelledInput.tsx
- src/components/Pill/Pill.tsx
- src/components/SortDropdown/SortDropdown.tsx
- src/containers/MobileFilterHeader.tsx
- src/hooks/useRangeFacet.ts
- src/styles/index.css
Changes for [WAF-396](https://amersports.atlassian.net/browse/WAF-396)
> Waf 396 filters 2

- dev-template.html
- src/api/search.ts
Currently filter by pcm_product_salability is breaking search in slugger.
We disable it temporarily
> Disable salability filter

- src/containers/MobileFilterHeader.tsx
filter side bar are now always hidden by default. most noticeab in cases of custom categories.
https://amersports.atlassian.net/browse/WAF-473
> WAF-473 - filter side bar visibility change

- dev-template.html
- src/context/products.tsx
- src/types/interface.ts
Sort franchises and category filter based on categoryExtraInfo order
> WAF-633 - Sort franchise based on categoryExtraInfo order

- src/components/SwatchButton/SwatchButton.tsx
https://amersports.atlassian.net/browse/WAF-580
Added replace in case there are ASCII quotes in image URL.
> WAF-580 - Replacing ASCI with sign

- src/components/Facets/Facets.tsx
- src/components/Facets/ToggleFilters.tsx
- src/components/FilterSelection/FilterSelection.tsx
- src/components/InputButtonGroup/InputButtonGroup.tsx
- src/components/SortDropdown/SortDropdown.tsx
[WAF-507](https://amersports.atlassian.net/browse/WAF-507)
Added keyboard navigation for tabs and main filter activation
> WAF-507 - Keyboard navigation for filters

- src/components/Pagination/Pagination.tsx
Classes change for [WAF-518](https://amersports.atlassian.net/browse/WAF-518)
> WAF-518 - Changing stroke weight on pagination

- src/components/Facets/FranchiseViewSelector.tsx
- src/components/Facets/filters.css
- src/containers/MobileFilterHeader.tsx
- src/styles/index.css
As required by [WAF-545](https://amersports.atlassian.net/browse/WAF-545)
> WAF-545 - Franchise selector for mobile change

- src/utils/getProductImage.ts
- src/utils/productUtils.ts
Jira : https://amersports.atlassian.net/browse/WAF-628
Avoid js error on search page when a product has no color options like here https://main--wilson--wilson-ecommerce.aem.live/en-us/search?q=everyday
> WAF-628 - Update search and remove error js when no color options

- src/components/Loading/Loading.tsx
- src/containers/App.tsx
- src/styles/index.css
https://github.com/wilson-ecommerce/eds-amersports/pull/515
> remove below-title enrichment

- src/components/ProductList/ProductList.tsx
Fix js error on plp
https://amersports.atlassian.net/browse/WAF-741
> WAF-720 - Fix error js

- src/components/FilterSelection/FilterSelection.tsx
- src/containers/MobileFilterHeader.tsx
- src/containers/ProductsHeader.tsx
Fixed wrong width of filter button/activator for mobile and tablet
[WAF-649](https://amersports.atlassian.net/browse/WAF-649)
> WAF-649 - Fix for tablet/mobile look

- src/components/Facets/filters.css
- src/containers/MobileFilterHeader.tsx
Added back filter pills on mobile with new design per Erika request
[WAF-653](https://amersports.atlassian.net/browse/WAF-653)
> WAF-653 - Mobile filter pills return

- src/components/Pagination/Pagination.tsx
[WAF-518](https://amersports.atlassian.net/browse/WAF-518)
> WAF-518 - QuickFix for missed classname template error

- src/components/Facets/SelectedFilters.tsx
- src/containers/MobileFilterHeader.tsx
Little fix after testing on Quals.
[WAF-653](https://amersports.atlassian.net/browse/WAF-653)
> WAF-653 - Double franchise fix

- src/components/ProductList/ProductList.tsx
- src/styles/index.css
https://amersports.atlassian.net/browse/WAF-355
spacing fix for PLP
> WAF-355 - spacing fix

- src/components/Facets/Facets.tsx
Sort size similar to Champions
> WAF-657 - Sorted sizes

- src/containers/App.tsx
https://amersports.atlassian.net/browse/WAF-775
> WAF-775 - Update search title for wilson

- src/components/InputButtonGroup/InputButtonGroup.tsx
- src/components/LabelledInput/LabelledInput.tsx
https://amersports.atlassian.net/browse/WAF-521
> WAF-521 - Remove title 0 filters

- dev-template.html
- src/utils/getProductImage.ts
https://amersports.atlassian.net/browse/WAF-842
change image from attribute to use the small image property instead
> WAF-842 - changed to small_image on product load

- dev-template.html
- src/components/ProductItem/ProductItem.tsx
- src/utils/getProductImage.ts
https://amersports.atlassian.net/browse/WAF-889
> WAF-889 - added logic check for bundle images

- src/components/InputButtonGroup/InputButtonGroup.tsx
[WAF-956](https://amersports.atlassian.net/browse/WAF-956)
> WAF-956 - Fix for category name label in filters

- src/containers/MobileFilterHeader.tsx
- src/i18n/en_US.ts
- src/utils/sort.ts
https://amersports.atlassian.net/browse/WAF-1139
> WAF-1139 - added new logic for sort options (New and renamed Featured)

- src/components/ProductItem/ProductPrice.tsx
[WAF-1073](https://amersports.atlassian.net/browse/WAF-1073)
> WAF-1073 - Promo price switch

- src/containers/MobileFilterHeader.tsx
[WAF-827](https://amersports.atlassian.net/browse/WAF-827)
> WAF-827 - Mobile fix

- dev-template.html
- src/utils/productUtils.ts
https://amersports.atlassian.net/browse/WAF-1200
> WAF-1200 - fixed missing id on default color swatch

- src/components/Facets/SelectedFilters.tsx
- src/components/ProductList/product-list.css
[waf-827](https://amersports.atlassian.net/browse/WAF-827)
> WAF-827 - Fixes for mobile

- src/components/ProductItem/ProductItem.tsx
- src/context/products.tsx
- src/utils/productUtils.ts
https://amersports.atlassian.net/browse/WAF-1232
> WAF-1232 - updated logic to get product IDs for badges

- src/utils/getProductPrice.ts
https://amersports.atlassian.net/browse/WAF-1212
> WAF-1212 - plp price format for euros

- src/components/MobileFacets/MobileFacets.tsx
- src/components/SortDropdown/SortDropdown.tsx
[WAF-708](https://amersports.atlassian.net/browse/WAF-708)
> WAF-708 - Change for keyboard navigation

- src/components/SwatchButton/SwatchButton.tsx
- src/components/SwatchButtonGroup/SwatchButtonGroup.tsx
- src/icons/chevron-right.svg
Reverts wilson-ecommerce/storefront-product-listing-page#149
> Revert "WAF-387 - Add arrow on swatches in progress"

- src/api/graphql.ts
- src/api/search.ts
- src/components/ProductItem/ProductItem.tsx
- src/components/ProductList/ProductList.test.tsx
- src/components/ProductList/ProductList.tsx
- src/containers/ProductsContainer.tsx
- src/context/events.tsx
- src/context/products.tsx
- src/types/interface.ts
Reverts wilson-ecommerce/storefront-product-listing-page#158
> Revert "WAF-1420 - Revert"

- src/api/search.ts
removed id, priceRange, RatingCount, RatingAverage, optionID, and season from the search-response-received and search-results-view events
ticket: https://amersports.atlassian.net/browse/WAF-1401
> wilson eventing fix

- src/api/search.ts
- src/components/ImageHover/ImageHover.tsx
- src/components/ProductItem/ProductItem.tsx
- src/components/ProductList/ProductList.tsx
- src/utils/getProductImage.ts
[WAF-1374 ](https://amersports.atlassian.net/browse/WAF-1374) + lint fixes
> WAF-1374 - Category Id for franchise + lint error fixes
